CREATE TABLE IF NOT EXISTS Tickets (
	Id SERIAL PRIMARY KEY,
	Price DECIMAL NOT NULL,
	Buyer_name VARCHAR(100) NOT NULL,
	Bought_date DATE NOT NULL,
	Session_date DATE NOT NULL,
	Special_id INTEGER NOT NULL,
	Seat_place INTEGER NOT NULL,
	Row_place INTEGER NOT NULL,
	Hall VARCHAR(50) NOT NULL
)