CREATE TABLE IF NOT EXISTS Films (
	Id SERIAL PRIMARY KEY, 
	Title VARCHAR(150) NOT NULL,
	Age_rating INTEGER NOT NULL,
	Genre VARCHAR (50) NOT NULL,
	Author VARCHAR(100) NOT NULL,
	Description VARCHAR(230) NOT NULL,
	Rating NUMERIC
)